spring.application.name=loans
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/prueba
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
spring.security.user.name=admin
spring.security.user.password=admin123

jwt.secret=pX3k8!m9#qR2vB7$wZ1tL6@fH4yD0sJ8
# jwt.expiration-ms es 2 horas en milisegundos
jwt.expiration-ms=7200000

# Logging
logging.level.root=INFO
